var landen = [
// Afrika
	"Algerije",
	"Angola",
	"Benin",
	"Botswana",
	"Burkina Fasso",
	"Burundi",
	"Centraal Afrikaanse Republiek",
	"Chaad",
	"De Comoren",
	"Djibouti",
	"Egypte",
	"Equatoriaal Guinea",
	"Eritrea",
	"Ethiopië",
	"Gabon",
	"Gambia",
	"Ghana",
	"Guinea",
	"Guinea-Bissau",
	"IvoorKust",
	"Kaap Verdië",
	"Kameroen",
	"Kenia",
	"Kongo",
	"Lesotho",
	"Liberia",
	"Libië",
	"Madagascar",
	"Malawi",
	"Mali",
	"Mauritanië",
	"Mauritius",
	"Marokko",
	"Mozambique",
	"Namibië",
	"Niger",
	"Nigeria",
	"Oeganda",
	"Rwanda",
	"Sao Tomë© en Principe",
	"Senegal",
	"Seychellen",
	"Sierra Leone",
	"Somalië",
	"Soedan",
	"Swaziland",
	"Tanzania",
	"Togo",
	"Tunesië",
	"Zambia",
	"Zimbabwe",
	"Zuid Afrika",
	"Zuid Soedan",
	// Azië
	"Afghanistan",
	"Bahrein",
	"Bangladesh",
	"Bhutan",
	"Brunei",
	"Burma (Myanmar)",
	"Cambodia",
	"China",
	"India",
	"Indonesië",
	"Iran",
	"Irak",
	"Israël",
	"Japan",
	"Jordanië",
	"Kazakhstan",
	"Koeweit",
	"Kyrgyzstan",
	"Laos",
	"Libanon",
	"Maleisië",
	"Malediven",
	"Mongolië",
	"Nepal",
	"Noord Korea",
	"Oezbekistan",
	"Oman",
	"Oost Timor",
	"Pakistan",
	"Philippijnen",
	"Qatar",
	"Rusland",
	"Saudi Arabië",
	"Singapoor",
	"Sri Lanka",
	"Syrië",
	"Tajikistan",
	"Thailand",
	"Turkije",
	"Turkmenistan",
	"Verenigde Arabische Emiraten",
	"Vietnam",
	"Yemen",
	"Zuid Korea",
	// Europa
	"Albanië",
	"Andorra",
	"Armenië",
	"Azerbaijan",
	"België",
	"Bosnië en Herzegovina",
	"Bulgarië",
	"Cyprus",
	"Denemarken",
	"Estland",
	"Finland",
	"Frankrijk",
	"Georgië",
	"Duitsland",
	"Griekenland",
	"Hongarije",
	"IJsland",
	"Ierland",
	"Italë",
	"Kroatië",
	"Letland",
	"Liechtenstein",
	"Litouwen",
	"Luxemburg",
	"Macedonië",
	"Malta",
	"Moldova",
	"Monaco",
	"Montenegro",
	"Nederland",
	"Noorwegen",
	"Oekraëne",
	"Oostenrijk",
	"Polen",
	"Portugal",
	"Romanië",
	"San Marino",
	"Servië",
	"Slovakije",
	"Slovenenië",
	"Spanje",
	"Tsechië",
	"Vaticaanstad",
	"Verenigd Koninkrijk",
	"Wit Rusland",
	"Zweden",
	"Zwitzerland",
	// Noord Amerika
	"Antigua en Barbuda",
	"Bahama's",
	"Barbados",
	"Belize",
	"Canada",
	"Costa Rica",
	"Cuba",
	"Dominica",
	"Dominicaanse Republiek",
	"El Salvador",
	"Grenada",
	"Guatemala",
	"Haïti",
	"Honduras",
	"Jamaica",
	"Mexico",
	"Nicaragua",
	"Panama",
	"St. Kitts & Nevis",
	"St. Lucia",
	"St. Vincent en de Grenadines",
	"Trinidad & Tobago",
	"Verenigde Staten",
	// Oceanië
	"Australië",
	"Fiji eilanden",
	"Kiribati",
	"Marshall Eilanden",
	"Micronesië",
	"Nauru",
	"Nieuw Zeeland",
	"Palau",
	"Papua Nieuw Guinea",
	"Samoa",
	"Solomon Eilanden",
	"Tonga",
	"Tuvalu",
	"Vanuatu",
	// Zuid Amerika
	"Argentinië",
	"Bolivia",
	"Brazilië",
	"Chili",
	"Colombia",
	"Ecuador",
	"Guyana",
	"Paraguay",
	"Peru",
	"Suriname",
	"Uruguay",
	"Venezuela"
];
 let aanvuller = new AutomatischAanvuller();

 aanvuller.init('landen', landen);
 document.getElementById('landen').focus();
